#!/bin/sh -e

get_repo_entry () {
	local mpkfile=$1
	local cksum=`sha256sum $mpkfile | cut -f1 -d' '`
	tar -xf $mpkfile -O ./MMPACK/info
	echo "    filename: $mpkfile"
	echo "    sha256: $cksum"
}

if [ $# -ne 1 ]; then
	echo "Usage: $0 <srv_datadir>"
	exit 1
fi

srcdir=`dirname $0`
srvdata=$1
builddir=$srvdata/build
mpkpool=$srvdata/pool

# cleanup previous run
rm -rf $builddir
rm -rf $mpkpool

# Generate binary packages
mkdir -p $mpkpool
$srcdir/create-mpks $builddir $mpkpool

# Create repo index
cd $srvdata
for f in pool/*.mpk
do
	get_repo_entry $f
done > binary-index

# Start HTTP server (only local connections are accepted)
exec python3 -m http.server 8888 --bind 127.0.0.1
