#!/bin/sh

tooldir=`dirname $0`
nproc=$(grep -c "processor" /proc/cpuinfo)
nproc=${nproc:-1}

pycodestyle --show-source $*
style_exitcode=$?

pylint3 --jobs=$nproc --disable=locally-disabled --rcfile=$tooldir/pylint-config $*
lint_exitcode=$?

[ $style_exitcode -ne 0 ] && exit 1
exit $lint_exitcode
