#!/bin/sh
set -e

if ! getent passwd mmpack-builder >/dev/null; then
	adduser --quiet \
	        --no-create-home --home /var/lib/mmpack-gerrit-builder \
	        --system --disabled-password --shell /bin/sh \
	        --gecos "MMPACK builder,,," \
		mmpack-builder

	if ! [ -d /var/lib/mmpack-gerrit-builder ]; then
		mkdir -p /var/lib/mmpack-gerrit-builder
		chown mmpack-builder:root /var/lib/mmpack-gerrit-builder
	fi
fi

#DEBHELPER#

exit 0
